---
title: 'Post 3'
---

I’ve been using the term “raw” to describe data since my first semester at Smith College when I was introduced to data science.  I thought it was quite funny actually — to refer to spreadsheets of numbers and text in the same way that we talk about cookie dough or a skinned knee.  It wasn’t until the beginning of this semester, three years later, that I began to question this diction.  Sitting in on Prof. Brent Durbin’s seminar discussion a few weeks ago, he said something along the lines of, “I have this theory that data are always pre-cooked, never raw.”  He even centers this concept in the title of his book in the works *Cooked: A Politics History of Data*.  This same sentiment was echoed by D’Ignazio and Klein in *Data Feminism* Chapter 2: Collect, Analyze, Imagine, Teach: “[T]he data are never “raw.” Data are always the product of unequal social relations—relations affected by centuries of history.”

What difference could one adjective make?  “Raw” assumes that the data is untainted which is untrue.  There’s a misconception that any and all bias in data science happens in the analysis process — in creating algorithms and models.  But, in reality, the choices made in the data collection process are just as skewed.  Picking and choosing what questions to ask, what data to collect, and where to collect said data all require careful allocation of time and resources — and more often than not, these choices narrow down the beneficiaries to leave out minoritized groups.  Because the data science field is dominated by cis white male voices, its no surprise that data is qualified as “raw” with the underlying notion that there’s no alternative form.  Reframing the way we talk about data and realizing that there is no such thing as “raw” data could push us to expose the flaws in the system that make the data “cooked” from conception.
