---
title: 'Post 1'
---

In her 2019 New Yorker article “What Statistics Can and Can’t Tell Us About Ourselves,”^[https://www.newyorker.com/magazine/2019/09/09/what-statistics-can-and-cant-tell-us-about-ourselves] mathematician Hannah Fry tells the story of a renowned doctor who was later convicted as a serial killer.  In Dr. Harold Shipman’s twenty-three years as a practitioner, he “injected at least two hundred and fifteen of his patients with lethal doses of opiates.”  How did Shipman get away with his heinous hobby for so long?  And, how could a critical pattern like this be identified earlier?  Turning to statistical analysis for these answers highlighted an inherent flaw of relying entirely on numbers rather than individual stories: “The number of his older patients who had died in the course of his career over the number that would be expected of an average doctor’s.”  In this story, this important discrepancy was identified and investigated, but this is not always the case.  Data and models are too often manipulated to tell misleading stories.

Decades earlier in 1963, pioneer of the second-wave feminist movement Betty Friedan compiled a completely separate type of data into *The Feminine Mystique*. She told the stories of the gender-based discrimination that continued to plague women of her era. But, like in the analysis of Dr. Shipman’s murder streak, Freidan’s qualitative data did not tell the whole story, and, instead, it specifically centered the experiences of suburban white housewives while leaving out the lived experiences of non-white and/or poor women. Nuance is challenging to capture with summaries of experiences whether that be through numbers like in Dr. Shipman’s case or sweeping statements like in Betty Friedan’s writing.  However, as pointed out in the introduction of *Data Feminism*^[https://data-feminism.mitpress.mit.edu/pub/frfa9szd/release/4], it’s important that we as statisticians and data scientists acknowledge this added hurdle and take initiative in exploring the world views of underrepresented populations.  

Attending a majorly liberal liberal arts college, it’s easy to remain comfortably enveloped in this alternative reality; critical thought, examination of bias, and discussion of intersectionality is key to our everyday lives. As budding data scientists, statisticians, and young professionals on the cusp of entering a new phase of life and leaving the social-justice woven nest of Smith, it’s crucial that we continue to pay close attention to our own assumptions, remain skeptical, seek the truth just as Catherine D'Ignazio and Lauren Klein the authors of *Data Feminism* do.
