---
title: 'Post 4'
---

This week I tried something new.  I listened to Chapters 3 and 4 of *Data Feminism*. Yes, listened.  I heard about this Google Chrome extension, Podcastle, on TikTok embarrassingly enough, and decided to give it a go.  It converts texts like newspaper articles or, in this case, an open-source textbook to podcast-style monologues read by an AI voice.  Of course I sped it up to 1.5x speed, but it also gave me the option to toggle between a “male” voice and a “female” voice.  This binary option felt especially relevant as I listened to the book section on “Rethinking Binaries in Data Visualization.”  I don’t have anything truly profound to say about this other than that it was no coincidence that this app only included two choices of voice and assigned them genders using tiny avatars — one with long hair and one with short hair.  There’s an option for me to give feedback, and because the app is so new and presumably maintained by a small team of developers, I think I could actually encourage them to rethink this feature of the app because it’s unnecessary and upholds this toxic societal assumption that there are only two genders.

As we read in *Data Feminism*, even companies who appear to be accounting for the spectrum of gender identities — by adding extra categories to their dropdown menus or, in the case of Facebook, leaving the option wide open by providing a blank text box — don’t always have the best intentions. Often, behind the scenes they are still maintaining their gender-based data by funneling people into a finite set of gender options, now aided by machine learning algorithms.  This ties back to our class discussions about the role that capitalism plays in defining how we use data.  If there wasn’t a push from companies to use gender-specific advertising to target whole groups, there might not be as much of a demand for sites like Facebook or Podcastle, to collect gender data.  But, on the other side of this, if determining gender and putting people into categories wasn’t such an integral part of society, capitalism might not be nearly as powerful as it is.  Capitalism, as it is right now, thrives on this kind of classification system —of race, gender, sex, socioeconmic status, etc. — and the classification system feeds off of capitalism.
